import time
name = input("escribe tu nombre")
loop = True
timer = 0

while loop == True:
#Prologo--------------------------------------------------------------------------------------------------------------------------------------
 time.sleep (5)
 print(f"{name} se despierta para comenzar otro dia para trabajar")
 time.sleep (2)
 print("mira el relog y se da cuenta que son las 8:30am")
 time.sleep (2)
 print("Te levantas rapido y piensas...")
 time.sleep (2)
 print("OTRA VEZ ME LEVANTE TARDE!!!")
 time.sleep (1)
 print("solo tengo 30 minutos para llegar al trabajo")
 time.sleep (1)
 print("Pero tengo mucha hambre...")
 time.sleep (2)
 print(f"¿que haras {name}?")
 answer = input("COMER / TRABAJAR")
 
 if answer == "COMER":
     print("Decidiste comer...")
     time.sleep (2)
     timer -= 1
 elif answer == "TRABAJAR":
     print("Decidiste ir a trabajar...")
     time.sleep (2)
 else:
     print("Repuesta no clara, porfavor escriba la respuesta que esta arriba en mayuscula o si no la elegire automaticamente")
     time.sleep (3)
     print("Decidiste ir a trabajar...")
     time.sleep (2)
#Juego-------------------------------------------------------------------------------------------------------------------------------------
 if timer == 0:
     time.sleep(1)
     print(f"Como decidiste trabajar antes de desayunar, llegaras a tiempo al trabajo")
     ending = "Domingo"
 else: #timer -1
     time.sleep(1)
     print(f"Como decidiste comer antes de trabajar, llegaras tarde al trabajo")
     time.sleep(1)
     print("Entoces ya siendo las 8:55am, Prendes tu carro y vas lo mas rapido que puede...")
     time.sleep(1)
     print("Pero al frente ves un policia vijilando la carretera y asegurandose que ningun carro valla mas de 80km")
     time.sleep(1)
     print("¿Deseas bajar la velocidad?")
     answer1 = input("SI / NO")
     if answer1 == "SI":
         time.sleep(1)
         print("Decidiste reducir la velocidad...")
         time.sleep(2)
         print("Pasas sin ningun problema, pero ves que se formo un paro en la carretera...")
         time.sleep(1)
         print("Entoces miras al otro lado y ves que hay otra carretera pero esta conduce a una camino llenos de baches...")
         time.sleep(1)
         print("que podria dañar tu carro")
         time.sleep(2)
         print(f"¿Que piensas hacer {name}?")
         answer2 = input("ESPERAR / ARRIESGARME")
         if answer2 == "ESPERAR":
             time.sleep(1)
             print("Decidistes esperar...")
             time.sleep(2)
             print("El paro tardo 1 HORA")
             time.sleep(1)
             print("Ya super estresado y con ganas de devolverse a dormir")
             time.sleep(2)
             print(f"Encuentras que la calle esta siendo arreglada, y dices...")
             time.sleep(1)
             print("YA NO ME PUEDE IR PEOR ESTE DIA!!!")
             time.sleep(2)
             print(f"¿Que piensas hacer {name}?")
             answer3 = input("DEVOLVERSE / ATRAVESAR")
             if answer3 == "ATRAVESAR":
                 time.sleep(1)
                 print("Decidiste ir con todo...")
                 time.sleep(2)
                 print("Pasas por la calle toda destrozada y sin querer atropellas a un trabajador")
                 time.sleep(2)
                 print("Y aun peor a la esquina de la cuadra habia una patrulla que vio todo lo sucedidio")
                 time.sleep(2)
                 print(f"¿Que piensas hacer {name}?")
                 answer4 = input("FUGARSE / RENDIRSE")
                 if answer4 == "FUGARSE":
                     time.sleep(1)
                     print("Decidistes fugarte...")
                     time.sleep(2)
                     print("Apretas el acelerador y ya sin importarte tu trabajo, porque tecnicamente arruinaste tu vida...")
                     time.sleep(2)
                     print("Vas de camino hacia el desierto donde las autoridades no piensan seguirte")
                     time.sleep(1)
                     print("Pero sucede algo...")
                     time.sleep(1)
                     print("Unos almunos del kinder estan pasando por la carretera justo en este trajico momento, pero puedes girar hacia otra carretera...")
                     time.sleep(3)
                     print(f"¿Que piensas hacer {name}?")
                     answer5 = input("SEGUIR / CRUZAR")
                     if answer5 == "SEGUIR":
                         time.sleep(1)
                         print("Sin remordimiento alguno...")
                         time.sleep(2)
                         print("Atropellas a 7 de los 15 niños que habian y horrorizado...")
                         time.sleep(2)
                         print("los oficiales te dejan de seguir.")
                         time.sleep(1)
                         print("llegas al desierto donde encuentras una gasolineria y decides parar y hechar gasolina...")
                         time.sleep(5)
                         print("y tambien pensar que haras ahora con tu vida...")
                         ending = "BADGUY"
                     else: #5
                         time.sleep(1)
                         print("Decidistes cruzar...")
                         time.sleep(2)
                         print("Ahora tienes otro problema... la cuadra ahora esta cerrada por los policias")
                         time.sleep(2)
                         print("y no puedes dar la vuelta porque te vienen siguiendo muchas patrullas...")
                         time.sleep(2)
                         print("Pero ves que hay un callejon lo suficientemente grande como para que entre tu carro")
                         time.sleep(2)
                         print("pero los de las patrullas no")
                         time.sleep(2)
                         print(f"¿Que piensas hacer {name}?")
                         answer6 = input("RENDIRSE / JAMAS")
                         if answer6 == "JAMAS":
                          time.sleep(1)
                          print("Decidistes Nunca Rendirte...")
                          time.sleep(2)
                          print("Con la adrenalina al tope y el acelerador al fondo")
                          time.sleep(1)
                          print("Haces una maniobra que te permite milagrosamente cruzar y no matarte en el proceso...")
                          time.sleep(2)
                          print("Logras evadir la patrulla y por ende escapar al desierto...")
                          time.sleep(3)
                          ending = "Lobo Solitario"
                         else: #6
                          time.sleep(1)
                          print("Decidistes Rendirte...")
                          ending = "Prisionero"
                 else: #4
                  print("Decidiste Rendirte...")
                  ending = "Prisionero"
             else: #3
                time.sleep(1)
                print("Decidistes voler a tu casa...")
                ending = "No Sumiso"
         else: #2
            time.sleep(1)
            print("Decidistes arriesgarte...")
            time.sleep(2)
            print("Entoces vas pasando por los baches con solo 3 minutos restantes y escuchas un fuerte golpe...")
            time.sleep(2)
            print("De imediatamente el carro cae de un lado")
            time.sleep(1)
            print("entoces ya imaginandote lo peor decides bajarte y revisar que paso")
            time.sleep(2)
            print("Al parecer un caucho se exploto y no tienes uno de repuesto...")
            time.sleep(2)
            print(f"¿Que piensas hacer {name}?")
            answer7 = input("AYUDA / CAMINAR")
            if answer7 == "CAMINAR":
               time.sleep(1)
               print("Ironicamente, decidistes caminar...")
               time.sleep(2)
               print("Caminando por la ya irreconosible carretera te encuentras con un puente que justamente conecta a la calle donde esta tu trabajo...")
               time.sleep(3)
               print("Pero que desafortunadamente se encuentra partido a la mitad")
               time.sleep(2)
               print("entoces piensas...")
               time.sleep(1)
               print("Ese puente no esta taaaaan roto, tal vez lo podria saltar!")
               time.sleep(2)
               print(f"¿Que piensas hacer {name}? (Ok esto es estupido, no me digas que de verdad vas a saltar...)")
               answer8 = input("SALTAR / RENDIRSE")
               if answer8 == "SALTAR":
                  time.sleep(1)
                  print("...")
                  time.sleep(2)
                  print("Saltas... ves tu vida pasar, los momentos que eras feliz, los momentos donde tu mama te regañaba y sobre todo...")
                  time.sleep(5)
                  print("A no ya te caiste")
                  ending = "Estupido"
               else: #8
                  time.sleep(1)
                  print("GRACIAS A DIOS USASTE LA LOGICA :D")
                  time.sleep(2)
                  print("Te sientas y miras a tu alrededor y piensas...")
                  time.sleep(1)
                  print("Porque me esfuerzo tanto en algo que no me gusta... Algo que solo lo hago por dinero...")
                  time.sleep(2.5)
                  print("Entoces escuchas una voz familiar...")
                  time.sleep(1)
                  print("Es tu jefe y te dice:")
                  time.sleep(3)
                  print(f"{name}, Que haces aqui hoy es domingo no deberias de estar aqui...")
                  time.sleep(4)
                  print("Tu decepcionado y cansado al mismo tiempo te tiras a llorar, pero el jefe siendo por suerte alguien humano")
                  time.sleep(4)
                  print("Reconoce tu esfuerzo como trabajador y decide premiarte con un aumento en tu sueldo, prestarte un caucho y lo mejor...")
                  time.sleep(4)
                  print("Una parrillada que justamente estaba haciendo")
                  ending = "GOODBOY"
            else: #7
               time.sleep(1)
               print("Pediste ayuda...")
               ending = "TERCO"
     else: #1
      time.sleep(1)
      print(f"Decidistes acelerar...")
      time.sleep(3)
      print(f"El policia te persigue y te logra detener")
      ending = "Multa"

 if ending == "Domingo":
    time.sleep(3)
    print("llegaste al trabajo pero te diste cuenta que era domingo... FIN")
 elif ending == "BADGUY":
    time.sleep(3)
    print("As decidido cambiar tu vida pero no creo que eso justifique tus acciones y no creo que esa accion tan inprudente te deje vivir... FIN")
 elif ending == "GOODBOY":   
    time.sleep(3)
    print("Bueno, Al final ser un jala bola no es tan malo como te dicen XD... FIN")
 elif ending == "Lobo Solitario":
    time.sleep(3)
    print("As decidido cambiar tu vida aun que bueno eso signifique hacerle daño a una persona pero no creo que se valla a morir...creo. FIN")
 elif ending == "Estupido":
    time.sleep(3)
    print("Sin comentarios... FIN")
 elif ending == "Multa":
    time.sleep(3)
    print("Creo que era mas facil bajar la velocidad en vez de dejarse multar 500$... FIN")
 elif ending == "No Sumiso":
    time.sleep(3)
    print("Decidiste no darte mas mala vida y mira valio la pena porque era domino... FIN")
 elif ending == "Prisionero":
    time.sleep(3)
    print("Si por lo menos vas a cometer un delito piensalo dos veces porfavor... FIN")
 elif ending == "TERCO":   
    time.sleep(3)
    print("Una grua se lleva tu carro mientras reflexionas si de verdad vale trabajar por 20$... FIN")
 time.sleep(10)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 print("")
 time.sleep(0.1)
 #END-----------------------------------------------------------------------------------------------------------------------------------------